---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Importing Varibles OUTPUT
      include_vars: vars/output_vars

    - name: Importing Varibles OUTPUT
      include_vars: vars/Bastion-vpc

    - name: create a new EC2 key pair, returns generated private key
      ec2_key:
        name: my_keypair
        region: "{{region}}"
      register: my_var

    - name: storing
      copy:
        content: "{my_var.key.my_keypair}"
        dest: "./sample-key.pem"
        mode: 0600
      when: my_var.changed

    - name: security group
      ec2_security_group:
        name: Bastion Host sh
        vpc_id: "{{vpcid}}"
        region: "{{region}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: BastionSG_out

    - name: Create Bastion Host
      ec2_instance:
        name: "public-compute-instance"
        key_name: "vprofile-key"
        region: "{{region}}"
        instance_type: t2.micro
        wait: yes
        wait_timeout: 300
        vpc_subnet_id: "{{pubsub1id}}"
        image_id: "{{bastion_ami}}"
        instance_tags:
          Name: "Bastion_host"
          project: vprofile
        exact_count: 1
        count_tag:
          Name: "Bastion_host"
          project: vprofile
        group_id: "{{BastionSG_out.group_id}}"
      register: bastionhost_out
