---
- hosts: localhost
  connection: local
  gather-facts: False
  tasks:
    name: create a vpc
    amazon.aws.ec2_vpc_net:
      name: "{{vpc_name}}"
      cidr_block: "{{vpcCidar}}"
      region: "{{region}}"
      dns_support: true
      dns_hostnames: true
      tags:
        module: ec2_vpc_net
        this: works
      tenancy: default
      state: "{{state}}"
