---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Importing Varibles
      include_vars: vars/Vpc-setup

    - name: create a vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: true
        dns_hostnames: true
        tags:
          module: ec2_vpc_net
          this: works
        tenancy: default
        state: "{{state}}"
      register: vpcout

    - debug:
        var: vpcout
