---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Importing Varibles
      include_vars: vars/Vpc-setup

    - name: create a vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: true
        dns_hostnames: true
        tags:
          module: ec2_vpc_net
          this: works
        tenancy: default
        state: "{{state}}"
      register: vpcout

    - debug:
        var: vpcout

      #Public subnet
    - name: Create subnet for PubSub1Cidr
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PubSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        map_public: yes
        resource_tags:
          Name: PubSub1Cidr
      register: PubSub1_out

    - name: Create subnet for PubSub2Cidr
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PubSub2Cidr}}"
        region: "{{region}}"
        az: "{{zone2}}"
        map_public: yes
        resource_tags:
          Name: PubSub2Cidr
      register: PubSub2_out

    - name: Create subnet for PubSub3Cidr
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PubSub3Cidr}}"
        region: "{{region}}"
        az: "{{zone3}}"
        map_public: yes
        resource_tags:
          Name: PubSub3Cidr
      register: PubSub3_out

    #Private subnet
    - name: Create subnet for PrivSub1Cidr
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PrivSub4Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        map_public: yes
        resource_tags:
          Name: PrivSub1Cidr
      register: PrivSub1_out

    - name: Create subnet for PrivSub2Cidr
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PrivSub5Cidr}}"
        region: "{{region}}"
        az: "{{zone2}}"
        map_public: yes
        resource_tags:
          Name: PrivSub2Cidr
      register: PrivSub2_out

    - name: Create subnet for PrivSub3Cidr
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PrivSub6Cidr}}"
        region: "{{region}}"
        az: "{{zone3}}"
        map_public: yes
        resource_tags:
          Name: PrivSub3Cidr
      register: PrivSub3_out
#  Internet gateway
    - name: Attach Internet Gateway to VPC
      ec2_vpc_igw_association:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{ region }}"
        state: "{{state}}"
      register: igw_out
#  routes table
    - name: Set up public subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{ region }}"
        subnets:
          - "{{ PubSub1_out.subnet.id }}"
          - "{{ PubSub2_out.subnet.id }}"
          - "{{ PubSub3_out.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_out.gateway_id }}"
      register: pubRt_out
